name: SCAPE Tool Demonstration Website
vendor: SCAPE        
maintainer:
  name: Per Møldrup-Dalum
  email: pmd( AT )statsbiblioteket( DOT )dk
  name: Zeynep Pehlivanz
  email: pehlivanz( AT )bd( DOT )lip6( DOT )fr
